# Generated by Django 4.2.6 on 2023-11-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinisedBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('match', models.CharField(max_length=200)),
                ('bet', models.CharField(max_length=200)),
                ('bet_type', models.CharField(max_length=200)),
                ('bet_team', models.CharField(max_length=200)),
                ('bet_payout', models.CharField(max_length=200)),
                ('bet_spread', models.CharField(max_length=200)),
                ('bet_date', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('wager', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.CharField(max_length=200)),
                ('game_date_time', models.CharField(max_length=200)),
                ('team_away', models.CharField(max_length=200)),
                ('team_home', models.CharField(max_length=200)),
                ('spread_away', models.CharField(max_length=10)),
                ('spread_away_payout', models.CharField(max_length=10)),
                ('spread_home', models.CharField(max_length=10)),
                ('spread_home_payout', models.CharField(max_length=10)),
                ('total_points_away', models.CharField(max_length=10)),
                ('total_points_away_payout', models.CharField(max_length=10)),
                ('total_points_home', models.CharField(max_length=10)),
                ('total_points_home_payout', models.CharField(max_length=10)),
                ('money_line_away', models.CharField(max_length=10)),
                ('money_line_home', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlacedBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('match', models.CharField(max_length=200)),
                ('bet', models.CharField(max_length=200)),
                ('bet_type', models.CharField(max_length=200)),
                ('bet_team', models.CharField(max_length=200)),
                ('bet_payout', models.CharField(max_length=200)),
                ('bet_spread', models.CharField(max_length=200)),
                ('bet_date', models.CharField(max_length=200)),
                ('wager', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=200)),
                ('team_away', models.CharField(max_length=200)),
                ('team_home', models.CharField(max_length=200)),
                ('team_winner', models.CharField(max_length=200)),
                ('point_diff', models.IntegerField()),
                ('total_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('bank', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('record', models.CharField(max_length=200)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('pushes', models.IntegerField()),
            ],
        ),
    ]
